server:
  port: 11001
spring:
  application:
    name: dream-user-server   #指定注册到Eureka Server的应用名称
  cloud:
    inetutils:
#      preferredNetworks:
#        - 192.168.1.           #指定网段
      ignored-interfaces:
        - VM.*                  #忽略的网卡
    client:
      ipAddress: 192.168.1.159  #指定IP

#显示info信息
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

eureka:
  instance:
    preferIpAddress: true   #将IP注册到Eureka Server
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}    #实例ID设置成IP:端口的形式
  client:
    service-url:
      defaultZone: http://dream7788:dream7788@192.168.1.159:20001/eureka,http://dream7788:dream7788@192.168.1.159:20002/eureka,http://dream7788:dream7788@192.168.1.159:20003/eureka

feign:
  compression:
    request:
      enabled: true   #对请求进行压缩
      mime-types: text/xml,application/xml,application/json   #媒体类型
    response:
      enabled: true   #对响应进行压缩
  hystrix:
    enabled: true   #开启hystrix

