server:
  port: 20000
spring:
  application:
    name: dream-eureka-server   #指定注册到Eureka Server的应用名称
  cloud:
    inetutils:
#      preferredNetworks:
#        - 192.168.1.           #指定网段
      ignored-interfaces:
        - VM.*                  #忽略的网卡
    client:
      ipAddress: 192.168.1.159  #指定IP

#显示info信息
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

security:
  basic:
    enabled: true         #开启基于HTTP basic的认证
  user:
    name: dream7788       #配置登录的账户
    password: dream7788   #配置登录的密码

eureka:
  instance:
    preferIpAddress: true   #将IP注册到Eureka Server
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}    #实例ID设置成IP:端口的形式
  client:
    service-url:
      defaultZone: http://dream7788:dream7788@192.168.1.159:20000/eureka
    register-with-eureka: false #不要将自己注册到Eureka Server
    fetch-registry: false #不需要同步其他的Eureka Server节点的数据



