server:
  port: 20006
spring:
  application:
    name: dream-config-server   #指定注册到Eureka Server的应用名称
  cloud:
    inetutils:
#      preferredNetworks:
#        - 192.168.1.           #指定网段
      ignored-interfaces:
        - VM.*                  #忽略的网卡
    client:
      ipAddress: 192.168.1.159  #指定IP
    config:
      server:
        git:
          uri: http://guonanjun@git.dream7788.com/guonanjun/config.git    #配置Git仓库的地址
          username: guonanjun   #Git仓库的账户
          password: dream7788   #Git仓库的密码
          search-paths: dev     #搜索目录
          clone-on-start: true  #启动时加载配置文件
    bus:
      trace:
        enabled: true     #开启bus的跟踪
  rabbitmq:
    host: 192.168.1.88    #rabbitmq地址
    port: 5672            #rabbitmq端口
    username: guest      #rabbitmq用户名
    password: guest      #rabbitmq密码

encrypt:
  key: dream7788  #设置对称加密的密钥

security:
  basic:
    enabled: true   #开启基于HTTP basic的认证
  user:
    name: dream7788       #配置登录的账户
    password: dream7788   #配置登录的密码

#显示info信息
info:
  app:
    name: dream-config-server
    encoding: UTF-8
    java:
      source: 1.8.0_112
      target: 1.8.0_112

eureka:
  instance:
    preferIpAddress: true   #将IP注册到Eureka Server
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}    #实例ID设置成IP:端口的形式
  client:
    service-url:
      defaultZone: http://dream7788:dream7788@192.168.1.159:20001/eureka,http://dream7788:dream7788@192.168.1.159:20002/eureka,http://dream7788:dream7788@192.168.1.159:20003/eureka



